### ISSUE TITLE
Hello, I could not find the file "jrpc.h", may you help me? Thanks a lot!

### ISSUE THREAD

**Issue by gzc** [alex-sherman/edsm#1]

**Comment by alex-sherman** [comment]
Sorry about that, I should add a readme for the sample program. It uses the JRPC library I wrote which you can find at https://github.com/alex-sherman/libjrpc.

It is definitely not required to use an RPC library like this to communicate with the tasks, you could just use sockets or pipes. I just happened to be working on it at the time and thought it convenient to use.

Hope that helps.

**Comment by gzc** [comment]
Thanks a lot!            I love systems and many of your projects are very interesting like RPC and DSM. Thanks for sharing ^_^
