### ISSUE TITLE
Did your implementation like TreadMarks?

### ISSUE THREAD

**Issue by gzc** [alex-sherman/edsm#2]

**Comment by pddenhar** [comment]
We actually wrote a paper about the design of EDSM,you can read about the design choices we made here: [Extensible_Distributed_Shared_Memory__EDSM_.pdf](https://github.com/alex-sherman/edsm/files/65014/Extensible_Distributed_Shared_Memory__EDSM_.pdf)

EDSM actually uses a more granular approach to shared memory than Treadmarks. It synchronizes memory at a byte level granularity, while Treadmarks is page level.

**Comment by gzc** [comment]
Cool job and Thanks for sharing this paper!
